export const DEAL_STAGES = [
  'NEW_LEAD',
  'CONTACTED',
  'STARTED',
  'IN_PROGRESS',
  'REQUIREMENT_COLLECTED',
  'DEMO_SCHEDULED',
  'DEMO_COMPLETED',
  'QUOTATION_SENT',
  'NEGOTIATION',
  'PAYMENT_PENDING',
  'CONVERTED',
  'LOST',
  'FOLLOW_UP_LATER',
  'ON_HOLD',
  'INVALID_CONTACT'
] as const;
